/**
 * Seller Module — Comprehensive Dummy Data
 * All data used across the seller dashboard.
 * When backend is ready, replace these with API calls.
 */

// ─── Seller Profile ──────────────────────────────────────────────
export const sellerProfile = {
  id: 'SLR001',
  name: 'Rajesh Kumar',
  email: 'rajesh@mithilakart.com',
  phone: '9876543210',
  avatar: null,
  storeName: 'Mithila Heritage Store',
  storeLogo: null,
  storeBanner: null,
  storeDescription: 'Premium handcrafted products from the heart of Mithila. Authentic Madhubani art, Sujani embroidery, and artisan goods.',
  businessType: 'Sole Proprietorship',
  gstNumber: '10AABCU9603R1ZM',
  panNumber: 'ABCDE1234F',
  pickupAddress: {
    line1: '42, Artisan Colony',
    line2: 'Near Janaki Temple',
    city: 'Madhubani',
    state: 'Bihar',
    pincode: '847211',
    landmark: 'Opposite Community Hall',
  },
  bankDetails: {
    accountHolder: 'Rajesh Kumar',
    accountNumber: '1234567890123456',
    ifsc: 'SBIN0001234',
    bankName: 'State Bank of India',
    branch: 'Madhubani Main Branch',
    upi: 'rajesh@sbi',
  },
  joinedDate: '2024-06-15',
  isVerified: true,
  rating: 4.7,
  totalReviews: 328,
};

// ─── Dashboard Stats ─────────────────────────────────────────────
export const dashboardStats = {
  todayOrders: 24,
  pendingOrders: 8,
  completedOrders: 156,
  cancelledOrders: 5,
  revenue: 485000,
  previousRevenue: 412000,
  walletBalance: 124500,
  monthlyEarnings: 185000,
  totalProducts: 67,
  lowStockProducts: 8,
  returns: 3,
  totalCustomers: 1243,
  averageRating: 4.7,
  previousMonthOrders: 142,
  currentMonthOrders: 178,
};

// ─── Products ────────────────────────────────────────────────────
export const products = [
  {
    id: 'PRD001',
    title: 'Madhubani Painting — Fish Motif',
    shortDescription: 'Authentic handpainted Madhubani art on handmade paper',
    description: 'This exquisite Madhubani painting features the traditional fish motif, symbolizing prosperity and fertility. Each piece is hand-painted by skilled artisans from Madhubani, Bihar, using natural dyes and pigments. The intricate line work and vibrant colors make it a perfect addition to any art collection or home decor.',
    category: 'Handicraft',
    subcategory: 'Madhubani',
    brand: 'Mithila Heritage',
    sku: 'MH-MP-001',
    price: 2499,
    discountPrice: 1999,
    gst: 12,
    stock: 45,
    weight: 0.3,
    dimensions: { length: 40, width: 30, height: 0.5 },
    thumbnail: null,
    gallery: [],
    tags: ['madhubani', 'painting', 'handmade', 'art', 'traditional'],
    specifications: [
      { key: 'Material', value: 'Handmade Paper' },
      { key: 'Size', value: '40cm x 30cm' },
      { key: 'Technique', value: 'Traditional Madhubani' },
      { key: 'Colors', value: 'Natural Dyes' },
    ],
    highlights: ['100% Handmade', 'Natural Dyes', 'Certified Artisan', 'Gift Ready'],
    warranty: 'No warranty — handcrafted item',
    returnPolicy: '7-day return if damaged during shipping',
    shippingInfo: 'Ships within 2-3 business days. Packed with protective layer.',
    seo: { title: 'Madhubani Fish Painting | Mithila Heritage', description: 'Buy authentic Madhubani painting with fish motif. Handpainted by skilled artisans.' },
    status: 'active',
    sales: 124,
    views: 3456,
    rating: 4.8,
    reviewCount: 42,
    createdAt: '2024-08-15',
    updatedAt: '2025-03-20',
  },
  {
    id: 'PRD002',
    title: 'Sujani Embroidery Cushion Cover — Set of 2',
    shortDescription: 'Hand-embroidered Sujani work on cotton fabric',
    description: 'Beautiful Sujani embroidery cushion covers featuring traditional motifs from Mithila region. Each cover is hand-stitched by women artisans. The set includes two 16x16 inch cushion covers with zip closure.',
    category: 'Home & Living',
    subcategory: 'Decor',
    brand: 'Mithila Heritage',
    sku: 'MH-SC-002',
    price: 1299,
    discountPrice: 999,
    gst: 5,
    stock: 32,
    weight: 0.4,
    dimensions: { length: 40, width: 40, height: 2 },
    thumbnail: null,
    gallery: [],
    tags: ['sujani', 'embroidery', 'cushion', 'handmade', 'home-decor'],
    specifications: [
      { key: 'Material', value: 'Cotton' },
      { key: 'Size', value: '16 x 16 inches' },
      { key: 'Closure', value: 'Zip' },
      { key: 'Wash', value: 'Hand Wash Only' },
    ],
    highlights: ['Set of 2', 'Hand Embroidered', 'Zip Closure', 'Machine Washable'],
    warranty: 'No warranty',
    returnPolicy: '10-day return policy',
    shippingInfo: 'Ships within 3-5 business days',
    seo: { title: 'Sujani Cushion Cover Set', description: 'Buy Sujani embroidery cushion covers, hand-stitched by artisans.' },
    status: 'active',
    sales: 89,
    views: 2100,
    rating: 4.5,
    reviewCount: 28,
    createdAt: '2024-09-10',
    updatedAt: '2025-04-05',
  },
  {
    id: 'PRD003',
    title: 'Tikuli Art Coaster Set — Pack of 6',
    shortDescription: 'Ancient Tikuli art form on wooden coasters',
    description: 'Revive the ancient art of Tikuli with these gorgeous hand-painted wooden coasters. Each coaster features unique traditional patterns, making every piece one of a kind.',
    category: 'Handicraft',
    subcategory: 'Tikuli',
    brand: 'Mithila Heritage',
    sku: 'MH-TC-003',
    price: 899,
    discountPrice: null,
    gst: 12,
    stock: 5,
    weight: 0.6,
    dimensions: { length: 10, width: 10, height: 8 },
    thumbnail: null,
    gallery: [],
    tags: ['tikuli', 'coasters', 'art', 'wooden', 'gift'],
    specifications: [
      { key: 'Material', value: 'Teak Wood' },
      { key: 'Diameter', value: '9 cm' },
      { key: 'Finish', value: 'Lacquer Coated' },
    ],
    highlights: ['Pack of 6', 'Unique Designs', 'Cork Bottom', 'Gift Box'],
    warranty: '6 months against manufacturing defects',
    returnPolicy: '7-day return if damaged',
    shippingInfo: 'Ships within 2 business days',
    seo: { title: 'Tikuli Art Coasters', description: 'Handpainted Tikuli art coasters in teak wood.' },
    status: 'active',
    sales: 67,
    views: 1800,
    rating: 4.9,
    reviewCount: 19,
    createdAt: '2024-10-01',
    updatedAt: '2025-05-12',
  },
  {
    id: 'PRD004',
    title: 'Mithila Organic Honey — 500g',
    shortDescription: 'Pure organic honey from Mithila bee farms',
    description: 'Raw, unprocessed organic honey sourced directly from bee farms in the Mithila region. Rich in antioxidants and natural enzymes. No added sugars or preservatives.',
    category: 'Food & Grocery',
    subcategory: 'Organic',
    brand: 'Mithila Naturals',
    sku: 'MN-OH-004',
    price: 599,
    discountPrice: 499,
    gst: 0,
    stock: 120,
    weight: 0.55,
    dimensions: { length: 8, width: 8, height: 12 },
    thumbnail: null,
    gallery: [],
    tags: ['honey', 'organic', 'natural', 'pure', 'healthy'],
    specifications: [
      { key: 'Weight', value: '500g' },
      { key: 'Type', value: 'Multi-flora' },
      { key: 'Shelf Life', value: '24 months' },
    ],
    highlights: ['100% Organic', 'No Preservatives', 'Raw & Unprocessed', 'FSSAI Certified'],
    warranty: 'N/A',
    returnPolicy: 'Non-returnable food item',
    shippingInfo: 'Ships within 1-2 business days',
    seo: { title: 'Organic Honey 500g', description: 'Pure organic honey from Mithila.' },
    status: 'active',
    sales: 234,
    views: 5200,
    rating: 4.6,
    reviewCount: 78,
    createdAt: '2024-07-20',
    updatedAt: '2025-06-01',
  },
  {
    id: 'PRD005',
    title: 'Handloom Silk Saree — Tussar',
    shortDescription: 'Premium Tussar silk saree with Madhubani border',
    description: 'Elegant Tussar silk saree featuring traditional Madhubani art motifs on the border and pallu. Handwoven by master weavers. Comes with matching blouse piece.',
    category: 'Clothing',
    subcategory: 'Ethnic',
    brand: 'Mithila Weaves',
    sku: 'MW-SS-005',
    price: 8999,
    discountPrice: 7499,
    gst: 5,
    stock: 0,
    weight: 0.8,
    dimensions: { length: 30, width: 25, height: 5 },
    thumbnail: null,
    gallery: [],
    tags: ['saree', 'silk', 'tussar', 'handloom', 'traditional'],
    specifications: [
      { key: 'Fabric', value: 'Tussar Silk' },
      { key: 'Length', value: '5.5m with 0.9m blouse piece' },
      { key: 'Wash', value: 'Dry Clean Only' },
    ],
    highlights: ['Pure Tussar Silk', 'With Blouse Piece', 'Madhubani Border', 'Handwoven'],
    warranty: 'N/A',
    returnPolicy: '7-day return with tags intact',
    shippingInfo: 'Ships within 5-7 business days (made to order)',
    seo: { title: 'Tussar Silk Saree', description: 'Buy premium Tussar silk saree with Madhubani border.' },
    status: 'out_of_stock',
    sales: 56,
    views: 4100,
    rating: 4.9,
    reviewCount: 34,
    createdAt: '2024-11-05',
    updatedAt: '2025-05-28',
  },
  {
    id: 'PRD006',
    title: 'Makhana (Fox Nuts) — Premium Quality 250g',
    shortDescription: 'Grade A Makhana from Mithila farms',
    description: 'Premium quality Makhana sourced from the wetlands of Mithila. These fox nuts are handpicked, roasted, and packed fresh. Perfect for snacking, cooking, or festivities.',
    category: 'Food & Grocery',
    subcategory: 'Snacks',
    brand: 'Mithila Naturals',
    sku: 'MN-MK-006',
    price: 349,
    discountPrice: 299,
    gst: 5,
    stock: 200,
    weight: 0.28,
    dimensions: { length: 20, width: 12, height: 8 },
    thumbnail: null,
    gallery: [],
    tags: ['makhana', 'foxnuts', 'snack', 'healthy', 'organic'],
    specifications: [
      { key: 'Weight', value: '250g' },
      { key: 'Grade', value: 'A+' },
      { key: 'Shelf Life', value: '12 months' },
    ],
    highlights: ['Grade A+', 'Hand-Popped', 'No Additives', 'Vacuum Sealed'],
    warranty: 'N/A',
    returnPolicy: 'Non-returnable food item',
    shippingInfo: 'Ships within 1-2 business days',
    seo: { title: 'Premium Makhana 250g', description: 'Buy premium quality Makhana from Mithila.' },
    status: 'active',
    sales: 456,
    views: 8900,
    rating: 4.4,
    reviewCount: 112,
    createdAt: '2024-06-20',
    updatedAt: '2025-06-10',
  },
  {
    id: 'PRD007',
    title: 'Wooden Elephant — Hand Carved',
    shortDescription: 'Traditional hand-carved wooden elephant sculpture',
    description: 'Beautifully hand-carved wooden elephant made from seasoned sheesham wood. A traditional Mithila craft piece that represents strength and wisdom.',
    category: 'Handicraft',
    subcategory: 'Woodcraft',
    brand: 'Mithila Heritage',
    sku: 'MH-WE-007',
    price: 1899,
    discountPrice: 1599,
    gst: 12,
    stock: 3,
    weight: 1.2,
    dimensions: { length: 20, width: 10, height: 15 },
    thumbnail: null,
    gallery: [],
    tags: ['wooden', 'elephant', 'sculpture', 'handcarved', 'decor'],
    specifications: [
      { key: 'Material', value: 'Sheesham Wood' },
      { key: 'Height', value: '15 cm' },
      { key: 'Finish', value: 'Polish' },
    ],
    highlights: ['Hand Carved', 'Sheesham Wood', 'Eco-Friendly', 'Collectible'],
    warranty: '1 year against manufacturing defects',
    returnPolicy: '7-day return if damaged',
    shippingInfo: 'Ships within 3-5 business days',
    seo: { title: 'Wooden Elephant Sculpture', description: 'Buy hand-carved wooden elephant sculpture.' },
    status: 'active',
    sales: 34,
    views: 980,
    rating: 4.7,
    reviewCount: 11,
    createdAt: '2025-01-10',
    updatedAt: '2025-05-20',
  },
  {
    id: 'PRD008',
    title: 'Achar Gift Box — Assorted Pickles',
    shortDescription: '4 premium Mithila-style pickles in gift packaging',
    description: 'A curated gift box containing 4 varieties of authentic Mithila-style pickles — Mango, Lemon, Mixed Vegetable, and Green Chili. Made using traditional recipes with mustard oil.',
    category: 'Food & Grocery',
    subcategory: 'Spices',
    brand: 'Mithila Naturals',
    sku: 'MN-AG-008',
    price: 799,
    discountPrice: 699,
    gst: 12,
    stock: 85,
    weight: 1.0,
    dimensions: { length: 25, width: 20, height: 10 },
    thumbnail: null,
    gallery: [],
    tags: ['pickle', 'achar', 'gift', 'traditional', 'mithila'],
    specifications: [
      { key: 'Contents', value: '4 x 200g jars' },
      { key: 'Shelf Life', value: '18 months' },
      { key: 'Packaging', value: 'Premium Gift Box' },
    ],
    highlights: ['4 Flavors', 'Traditional Recipe', 'Gift Ready', 'No Preservatives'],
    warranty: 'N/A',
    returnPolicy: 'Non-returnable food item',
    shippingInfo: 'Ships within 2-3 business days',
    seo: { title: 'Mithila Pickle Gift Box', description: 'Buy assorted Mithila pickle gift box.' },
    status: 'draft',
    sales: 0,
    views: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: '2025-06-25',
    updatedAt: '2025-06-25',
  },
];

// ─── Orders ──────────────────────────────────────────────────────
export const orders = [
  {
    id: 'MK000142',
    customer: { name: 'Priya Sharma', email: 'priya@email.com', phone: '9876543211', avatar: null },
    products: [
      { id: 'PRD001', title: 'Madhubani Painting — Fish Motif', qty: 1, price: 1999, thumbnail: null },
      { id: 'PRD003', title: 'Tikuli Art Coaster Set — Pack of 6', qty: 2, price: 899, thumbnail: null },
    ],
    address: { line1: '12, Green Park', city: 'New Delhi', state: 'Delhi', pincode: '110016' },
    payment: { method: 'UPI', transactionId: 'TXN789456', status: 'paid' },
    status: 'delivered',
    totalAmount: 3797,
    shippingCharge: 0,
    discount: 200,
    finalAmount: 3597,
    placedAt: '2025-06-28T10:30:00',
    confirmedAt: '2025-06-28T11:00:00',
    packedAt: '2025-06-29T09:00:00',
    shippedAt: '2025-06-29T16:00:00',
    deliveredAt: '2025-07-01T14:30:00',
    trackingId: 'DLV2025062900012',
    notes: '',
  },
  {
    id: 'MK000143',
    customer: { name: 'Amit Verma', email: 'amit@email.com', phone: '9876543212', avatar: null },
    products: [
      { id: 'PRD004', title: 'Mithila Organic Honey — 500g', qty: 3, price: 499, thumbnail: null },
    ],
    address: { line1: '45, MG Road', city: 'Patna', state: 'Bihar', pincode: '800001' },
    payment: { method: 'COD', transactionId: null, status: 'pending' },
    status: 'pending',
    totalAmount: 1497,
    shippingCharge: 50,
    discount: 0,
    finalAmount: 1547,
    placedAt: '2025-07-06T08:15:00',
    confirmedAt: null,
    packedAt: null,
    shippedAt: null,
    deliveredAt: null,
    trackingId: null,
    notes: 'Customer requested gift wrapping',
  },
  {
    id: 'MK000144',
    customer: { name: 'Sneha Jha', email: 'sneha@email.com', phone: '9876543213', avatar: null },
    products: [
      { id: 'PRD005', title: 'Handloom Silk Saree — Tussar', qty: 1, price: 7499, thumbnail: null },
    ],
    address: { line1: '78, Lake Town', city: 'Kolkata', state: 'West Bengal', pincode: '700089' },
    payment: { method: 'Card', transactionId: 'TXN789457', status: 'paid' },
    status: 'shipped',
    totalAmount: 7499,
    shippingCharge: 0,
    discount: 500,
    finalAmount: 6999,
    placedAt: '2025-07-03T15:20:00',
    confirmedAt: '2025-07-03T16:00:00',
    packedAt: '2025-07-04T10:00:00',
    shippedAt: '2025-07-05T08:00:00',
    deliveredAt: null,
    trackingId: 'DLV2025070500045',
    notes: '',
  },
  {
    id: 'MK000145',
    customer: { name: 'Rahul Singh', email: 'rahul@email.com', phone: '9876543214', avatar: null },
    products: [
      { id: 'PRD006', title: 'Makhana (Fox Nuts) — Premium Quality 250g', qty: 5, price: 299, thumbnail: null },
      { id: 'PRD004', title: 'Mithila Organic Honey — 500g', qty: 1, price: 499, thumbnail: null },
    ],
    address: { line1: '22, Boring Road', city: 'Patna', state: 'Bihar', pincode: '800013' },
    payment: { method: 'UPI', transactionId: 'TXN789458', status: 'paid' },
    status: 'packed',
    totalAmount: 1994,
    shippingCharge: 40,
    discount: 100,
    finalAmount: 1934,
    placedAt: '2025-07-05T12:00:00',
    confirmedAt: '2025-07-05T13:00:00',
    packedAt: '2025-07-06T09:00:00',
    shippedAt: null,
    deliveredAt: null,
    trackingId: null,
    notes: '',
  },
  {
    id: 'MK000146',
    customer: { name: 'Anita Devi', email: 'anita@email.com', phone: '9876543215', avatar: null },
    products: [
      { id: 'PRD002', title: 'Sujani Embroidery Cushion Cover — Set of 2', qty: 3, price: 999, thumbnail: null },
    ],
    address: { line1: '5, Gandhi Maidan', city: 'Muzaffarpur', state: 'Bihar', pincode: '842001' },
    payment: { method: 'Card', transactionId: 'TXN789459', status: 'paid' },
    status: 'delivered',
    totalAmount: 2997,
    shippingCharge: 0,
    discount: 150,
    finalAmount: 2847,
    placedAt: '2025-06-25T09:00:00',
    confirmedAt: '2025-06-25T10:00:00',
    packedAt: '2025-06-26T08:00:00',
    shippedAt: '2025-06-26T15:00:00',
    deliveredAt: '2025-06-29T11:00:00',
    trackingId: 'DLV2025062600034',
    notes: '',
  },
  {
    id: 'MK000147',
    customer: { name: 'Vikash Kumar', email: 'vikash@email.com', phone: '9876543216', avatar: null },
    products: [
      { id: 'PRD007', title: 'Wooden Elephant — Hand Carved', qty: 1, price: 1599, thumbnail: null },
    ],
    address: { line1: '89, Sector 12', city: 'Noida', state: 'Uttar Pradesh', pincode: '201301' },
    payment: { method: 'UPI', transactionId: 'TXN789460', status: 'refunded' },
    status: 'cancelled',
    totalAmount: 1599,
    shippingCharge: 0,
    discount: 0,
    finalAmount: 1599,
    placedAt: '2025-07-02T17:30:00',
    confirmedAt: '2025-07-02T18:00:00',
    packedAt: null,
    shippedAt: null,
    deliveredAt: null,
    trackingId: null,
    notes: 'Cancelled by customer — wrong address',
  },
  {
    id: 'MK000148',
    customer: { name: 'Meera Kumari', email: 'meera@email.com', phone: '9876543217', avatar: null },
    products: [
      { id: 'PRD001', title: 'Madhubani Painting — Fish Motif', qty: 2, price: 1999, thumbnail: null },
    ],
    address: { line1: '15, Civil Lines', city: 'Darbhanga', state: 'Bihar', pincode: '846004' },
    payment: { method: 'COD', transactionId: null, status: 'pending' },
    status: 'pending',
    totalAmount: 3998,
    shippingCharge: 0,
    discount: 0,
    finalAmount: 3998,
    placedAt: '2025-07-06T11:45:00',
    confirmedAt: null,
    packedAt: null,
    shippedAt: null,
    deliveredAt: null,
    trackingId: null,
    notes: '',
  },
  {
    id: 'MK000149',
    customer: { name: 'Suman Jha', email: 'suman@email.com', phone: '9876543218', avatar: null },
    products: [
      { id: 'PRD006', title: 'Makhana (Fox Nuts) — Premium Quality 250g', qty: 10, price: 299, thumbnail: null },
    ],
    address: { line1: '3, Station Road', city: 'Saharsa', state: 'Bihar', pincode: '852201' },
    payment: { method: 'UPI', transactionId: 'TXN789462', status: 'paid' },
    status: 'delivered',
    totalAmount: 2990,
    shippingCharge: 0,
    discount: 300,
    finalAmount: 2690,
    placedAt: '2025-06-20T14:00:00',
    confirmedAt: '2025-06-20T15:00:00',
    packedAt: '2025-06-21T08:00:00',
    shippedAt: '2025-06-21T16:00:00',
    deliveredAt: '2025-06-24T10:00:00',
    trackingId: 'DLV2025062100022',
    notes: '',
  },
];

// ─── Returns ─────────────────────────────────────────────────────
export const returns = [
  {
    id: 'RTN001',
    orderId: 'MK000142',
    customer: { name: 'Priya Sharma', email: 'priya@email.com' },
    product: { id: 'PRD003', title: 'Tikuli Art Coaster Set — Pack of 6', price: 899 },
    reason: 'One coaster arrived cracked',
    customerImages: [],
    status: 'pending',
    refundAmount: 899,
    refundStatus: 'pending',
    requestedAt: '2025-07-02T10:00:00',
    timeline: [
      { date: '2025-07-02T10:00:00', event: 'Return requested by customer' },
      { date: '2025-07-02T10:05:00', event: 'Return request received' },
    ],
  },
  {
    id: 'RTN002',
    orderId: 'MK000146',
    customer: { name: 'Anita Devi', email: 'anita@email.com' },
    product: { id: 'PRD002', title: 'Sujani Embroidery Cushion Cover — Set of 2', price: 999 },
    reason: 'Color does not match the image shown',
    customerImages: [],
    status: 'approved',
    refundAmount: 999,
    refundStatus: 'processed',
    requestedAt: '2025-06-30T09:00:00',
    timeline: [
      { date: '2025-06-30T09:00:00', event: 'Return requested by customer' },
      { date: '2025-06-30T11:00:00', event: 'Return approved by seller' },
      { date: '2025-07-01T14:00:00', event: 'Product picked up' },
      { date: '2025-07-03T10:00:00', event: 'Refund processed' },
    ],
  },
  {
    id: 'RTN003',
    orderId: 'MK000149',
    customer: { name: 'Suman Jha', email: 'suman@email.com' },
    product: { id: 'PRD006', title: 'Makhana (Fox Nuts) — Premium Quality 250g', price: 299 },
    reason: 'Received expired product',
    customerImages: [],
    status: 'rejected',
    refundAmount: 0,
    refundStatus: 'not_applicable',
    requestedAt: '2025-06-26T08:00:00',
    timeline: [
      { date: '2025-06-26T08:00:00', event: 'Return requested by customer' },
      { date: '2025-06-26T14:00:00', event: 'Return rejected — product within shelf life' },
    ],
  },
];

// ─── Customers ───────────────────────────────────────────────────
export const customers = [
  { id: 'CUS001', name: 'Priya Sharma', email: 'priya@email.com', phone: '9876543211', orders: 8, totalSpend: 24500, avgOrderValue: 3062, lastOrder: '2025-07-01', joinedAt: '2024-08-10', notes: 'VIP customer, repeat buyer' },
  { id: 'CUS002', name: 'Amit Verma', email: 'amit@email.com', phone: '9876543212', orders: 3, totalSpend: 4500, avgOrderValue: 1500, lastOrder: '2025-07-06', joinedAt: '2025-01-15', notes: '' },
  { id: 'CUS003', name: 'Sneha Jha', email: 'sneha@email.com', phone: '9876543213', orders: 5, totalSpend: 32000, avgOrderValue: 6400, lastOrder: '2025-07-03', joinedAt: '2024-11-20', notes: 'Prefers silk products' },
  { id: 'CUS004', name: 'Rahul Singh', email: 'rahul@email.com', phone: '9876543214', orders: 12, totalSpend: 18900, avgOrderValue: 1575, lastOrder: '2025-07-05', joinedAt: '2024-06-25', notes: 'Bulk buyer — food items' },
  { id: 'CUS005', name: 'Anita Devi', email: 'anita@email.com', phone: '9876543215', orders: 6, totalSpend: 15600, avgOrderValue: 2600, lastOrder: '2025-06-25', joinedAt: '2024-09-05', notes: '' },
  { id: 'CUS006', name: 'Vikash Kumar', email: 'vikash@email.com', phone: '9876543216', orders: 2, totalSpend: 3200, avgOrderValue: 1600, lastOrder: '2025-07-02', joinedAt: '2025-03-10', notes: '' },
  { id: 'CUS007', name: 'Meera Kumari', email: 'meera@email.com', phone: '9876543217', orders: 4, totalSpend: 8000, avgOrderValue: 2000, lastOrder: '2025-07-06', joinedAt: '2024-12-01', notes: 'Art collector' },
  { id: 'CUS008', name: 'Suman Jha', email: 'suman@email.com', phone: '9876543218', orders: 15, totalSpend: 35000, avgOrderValue: 2333, lastOrder: '2025-06-20', joinedAt: '2024-06-18', notes: 'Top customer — corporate gifting' },
  { id: 'CUS009', name: 'Deepak Mishra', email: 'deepak@email.com', phone: '9876543219', orders: 1, totalSpend: 1999, avgOrderValue: 1999, lastOrder: '2025-05-15', joinedAt: '2025-05-15', notes: '' },
  { id: 'CUS010', name: 'Kavita Rani', email: 'kavita@email.com', phone: '9876543220', orders: 7, totalSpend: 21000, avgOrderValue: 3000, lastOrder: '2025-06-30', joinedAt: '2024-07-22', notes: 'Prefers handloom' },
];

// ─── Reviews ─────────────────────────────────────────────────────
export const reviews = [
  { id: 'REV001', productId: 'PRD001', productTitle: 'Madhubani Painting — Fish Motif', customer: 'Priya Sharma', rating: 5, text: 'Absolutely stunning! The colors are so vibrant and the detail is incredible. Arrived well-packaged. Will definitely buy more!', photos: [], reply: 'Thank you so much, Priya! We are glad you loved it. 🙏', status: 'visible', createdAt: '2025-06-30T10:00:00' },
  { id: 'REV002', productId: 'PRD004', productTitle: 'Mithila Organic Honey — 500g', customer: 'Rahul Singh', rating: 4, text: 'Good quality honey, very thick and flavorful. Only wish the jar was glass instead of plastic. Still great value.', photos: [], reply: null, status: 'visible', createdAt: '2025-07-02T14:30:00' },
  { id: 'REV003', productId: 'PRD006', productTitle: 'Makhana (Fox Nuts) — Premium Quality 250g', customer: 'Suman Jha', rating: 5, text: 'Best makhana I have ever had! Perfectly roasted and crunchy. Ordering again for Diwali gifting.', photos: [], reply: null, status: 'visible', createdAt: '2025-06-25T09:00:00' },
  { id: 'REV004', productId: 'PRD002', productTitle: 'Sujani Embroidery Cushion Cover — Set of 2', customer: 'Anita Devi', rating: 3, text: 'Beautiful embroidery work but the color was slightly different from the photo. Decent quality fabric though.', photos: [], reply: 'We apologize for the color difference, Anita. Handmade items may have slight variations. We have updated our listing photos.', status: 'visible', createdAt: '2025-07-01T11:00:00' },
  { id: 'REV005', productId: 'PRD007', productTitle: 'Wooden Elephant — Hand Carved', customer: 'Vikash Kumar', rating: 5, text: 'This is a masterpiece! The carving detail is phenomenal. Bought it as a gift and my friend absolutely loved it.', photos: [], reply: null, status: 'visible', createdAt: '2025-07-04T16:00:00' },
  { id: 'REV006', productId: 'PRD001', productTitle: 'Madhubani Painting — Fish Motif', customer: 'Meera Kumari', rating: 4, text: 'Lovely painting. Authentic Madhubani art. Minor issue with frame alignment but the art itself is perfect.', photos: [], reply: null, status: 'visible', createdAt: '2025-07-05T08:00:00' },
  { id: 'REV007', productId: 'PRD003', productTitle: 'Tikuli Art Coaster Set — Pack of 6', customer: 'Deepak Mishra', rating: 2, text: 'Two coasters had paint chips on delivery. Packaging needs improvement.', photos: [], reply: null, status: 'visible', createdAt: '2025-07-03T13:00:00' },
  { id: 'REV008', productId: 'PRD006', productTitle: 'Makhana (Fox Nuts) — Premium Quality 250g', customer: 'Kavita Rani', rating: 5, text: 'Fresh, crunchy and tastes amazing! My go-to snack now. Mithila makhana is truly superior quality.', photos: [], reply: 'Thank you, Kavita! Happy to hear you enjoy our makhana. 😊', status: 'visible', createdAt: '2025-07-06T07:00:00' },
];

// ─── Coupons ─────────────────────────────────────────────────────
export const coupons = [
  { id: 'CPN001', code: 'FIRST50', type: 'percentage', value: 50, minOrder: 500, maxDiscount: 200, usageCount: 234, usageLimit: 500, expiryDate: '2025-09-30', status: 'active', createdAt: '2025-01-01' },
  { id: 'CPN002', code: 'MITHILA100', type: 'flat', value: 100, minOrder: 999, maxDiscount: 100, usageCount: 89, usageLimit: 200, expiryDate: '2025-08-15', status: 'active', createdAt: '2025-03-15' },
  { id: 'CPN003', code: 'DIWALI25', type: 'percentage', value: 25, minOrder: 1500, maxDiscount: 500, usageCount: 0, usageLimit: 1000, expiryDate: '2025-11-15', status: 'active', createdAt: '2025-06-01' },
  { id: 'CPN004', code: 'FLAT200', type: 'flat', value: 200, minOrder: 2000, maxDiscount: 200, usageCount: 150, usageLimit: 150, expiryDate: '2025-06-30', status: 'expired', createdAt: '2025-04-01' },
  { id: 'CPN005', code: 'HONEY10', type: 'percentage', value: 10, minOrder: 300, maxDiscount: 50, usageCount: 67, usageLimit: 100, expiryDate: '2025-12-31', status: 'active', createdAt: '2025-05-10' },
];

// ─── Notifications ───────────────────────────────────────────────
export const notifications = [
  { id: 'NTF001', type: 'order', title: 'New Order Received', message: 'Order #MK000148 placed by Meera Kumari for ₹3,998', read: false, createdAt: '2025-07-06T11:45:00' },
  { id: 'NTF002', type: 'order', title: 'New Order Received', message: 'Order #MK000143 placed by Amit Verma for ₹1,547', read: false, createdAt: '2025-07-06T08:15:00' },
  { id: 'NTF003', type: 'return', title: 'Return Request', message: 'Priya Sharma requested return for Tikuli Art Coaster Set', read: false, createdAt: '2025-07-02T10:00:00' },
  { id: 'NTF004', type: 'review', title: 'New Review', message: 'Meera Kumari left a 4-star review on Madhubani Painting', read: true, createdAt: '2025-07-05T08:00:00' },
  { id: 'NTF005', type: 'review', title: 'New Review', message: 'Deepak Mishra left a 2-star review on Tikuli Art Coaster Set', read: false, createdAt: '2025-07-03T13:00:00' },
  { id: 'NTF006', type: 'inventory', title: 'Low Stock Alert', message: 'Wooden Elephant — Hand Carved has only 3 units left', read: true, createdAt: '2025-07-04T09:00:00' },
  { id: 'NTF007', type: 'inventory', title: 'Low Stock Alert', message: 'Tikuli Art Coaster Set has only 5 units left', read: false, createdAt: '2025-07-05T10:00:00' },
  { id: 'NTF008', type: 'payment', title: 'Settlement Processed', message: 'Settlement #STL003 of ₹45,200 has been credited to your bank account', read: true, createdAt: '2025-07-01T12:00:00' },
  { id: 'NTF009', type: 'payment', title: 'Payout Pending', message: 'Settlement #STL004 of ₹38,600 is being processed', read: false, createdAt: '2025-07-05T14:00:00' },
  { id: 'NTF010', type: 'order', title: 'Order Delivered', message: 'Order #MK000142 has been delivered successfully to Priya Sharma', read: true, createdAt: '2025-07-01T14:30:00' },
];

// ─── Earnings & Transactions ─────────────────────────────────────
export const earningsData = {
  walletBalance: 124500,
  todayEarnings: 5600,
  weeklyEarnings: 38500,
  monthlyEarnings: 185000,
  yearlyEarnings: 1850000,
  totalLifetime: 4250000,
};

export const transactions = [
  { id: 'TRX001', type: 'credit', description: 'Order #MK000142 — Payment received', amount: 3597, date: '2025-07-01T14:30:00', status: 'completed' },
  { id: 'TRX002', type: 'credit', description: 'Order #MK000146 — Payment received', amount: 2847, date: '2025-06-29T11:00:00', status: 'completed' },
  { id: 'TRX003', type: 'debit', description: 'Platform commission — June batch', amount: 12500, date: '2025-07-01T00:00:00', status: 'completed' },
  { id: 'TRX004', type: 'debit', description: 'Refund — Return #RTN002', amount: 999, date: '2025-07-03T10:00:00', status: 'completed' },
  { id: 'TRX005', type: 'credit', description: 'Order #MK000149 — Payment received', amount: 2690, date: '2025-06-24T10:00:00', status: 'completed' },
  { id: 'TRX006', type: 'credit', description: 'Order #MK000145 — Payment received', amount: 1934, date: '2025-07-06T09:00:00', status: 'pending' },
  { id: 'TRX007', type: 'debit', description: 'Payout to bank account', amount: 50000, date: '2025-06-25T12:00:00', status: 'completed' },
  { id: 'TRX008', type: 'credit', description: 'Order #MK000144 — Payment received', amount: 6999, date: '2025-07-05T08:00:00', status: 'pending' },
];

export const settlements = [
  { id: 'STL001', period: 'June 1-15, 2025', amount: 85000, orders: 28, commission: 8500, netAmount: 76500, status: 'completed', paidAt: '2025-06-18T10:00:00' },
  { id: 'STL002', period: 'June 16-30, 2025', amount: 102000, orders: 35, commission: 10200, netAmount: 91800, status: 'completed', paidAt: '2025-07-03T10:00:00' },
  { id: 'STL003', period: 'July 1-6, 2025', amount: 45200, orders: 12, commission: 4520, netAmount: 40680, status: 'pending', paidAt: null },
];

// ─── Analytics Chart Data ────────────────────────────────────────
export const monthlySalesData = [
  { month: 'Jan', revenue: 120000, orders: 45 },
  { month: 'Feb', revenue: 135000, orders: 52 },
  { month: 'Mar', revenue: 158000, orders: 61 },
  { month: 'Apr', revenue: 142000, orders: 55 },
  { month: 'May', revenue: 175000, orders: 68 },
  { month: 'Jun', revenue: 195000, orders: 78 },
  { month: 'Jul', revenue: 185000, orders: 72 },
];

export const weeklySalesData = [
  { day: 'Mon', revenue: 12000, orders: 12 },
  { day: 'Tue', revenue: 19000, orders: 18 },
  { day: 'Wed', revenue: 15000, orders: 14 },
  { day: 'Thu', revenue: 22000, orders: 25 },
  { day: 'Fri', revenue: 30000, orders: 32 },
  { day: 'Sat', revenue: 45000, orders: 48 },
  { day: 'Sun', revenue: 40000, orders: 42 },
];

export const categorySalesData = [
  { name: 'Handicraft', value: 35, revenue: 245000 },
  { name: 'Food & Grocery', value: 30, revenue: 210000 },
  { name: 'Clothing', value: 20, revenue: 140000 },
  { name: 'Home & Living', value: 15, revenue: 105000 },
];

export const revenueData = [
  { date: 'Week 1', revenue: 42000, expenses: 8400 },
  { date: 'Week 2', revenue: 48000, expenses: 9600 },
  { date: 'Week 3', revenue: 55000, expenses: 11000 },
  { date: 'Week 4', revenue: 40000, expenses: 8000 },
];

// ─── Inventory Alerts ────────────────────────────────────────────
export const inventoryAlerts = [
  { productId: 'PRD003', title: 'Tikuli Art Coaster Set', stock: 5, threshold: 10, status: 'low' },
  { productId: 'PRD007', title: 'Wooden Elephant — Hand Carved', stock: 3, threshold: 10, status: 'low' },
  { productId: 'PRD005', title: 'Handloom Silk Saree — Tussar', stock: 0, threshold: 5, status: 'out' },
];

export const stockHistory = [
  { date: '2025-07-06', productId: 'PRD006', title: 'Makhana 250g', change: -5, type: 'sold', newStock: 200 },
  { date: '2025-07-05', productId: 'PRD001', title: 'Madhubani Painting', change: -2, type: 'sold', newStock: 45 },
  { date: '2025-07-04', productId: 'PRD007', title: 'Wooden Elephant', change: -1, type: 'sold', newStock: 3 },
  { date: '2025-07-03', productId: 'PRD004', title: 'Organic Honey', change: +50, type: 'restock', newStock: 120 },
  { date: '2025-07-02', productId: 'PRD002', title: 'Sujani Cushion Cover', change: -3, type: 'sold', newStock: 32 },
  { date: '2025-07-01', productId: 'PRD003', title: 'Tikuli Coasters', change: -2, type: 'sold', newStock: 5 },
];
